version: "2.0"
services:
  jenkins-etl:
    container_name: jenkins-local
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      inventory_store: ${inventory_store}
      inventory_store_key: ${inventory_store_key}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}